export const state = () => ({
  items: [
    {
      id: 1,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores eligendi eos eveniet fugiat labore minima pariatur perferendis perspiciatis reprehenderit vitae. Accusamus aperiam cum cupiditate, deserunt dolorem dolores ducimus eaque eius eligendi error esse excepturi facere id impedit in, incidunt, iure laborum modi molestias nesciunt optio perferendis possimus quae qui quo quod quos recusandae saepe sapiente sit soluta sunt temporibus vel veritatis vitae voluptas voluptate. Aliquam aperiam at culpa, deserunt eaque et iure libero magni modi nihil nulla odio perspiciatis, provident quas recusandae reprehenderit sed ullam voluptatibus! Asperiores debitis inventore ipsam molestias qui? Ducimus laboriosam quam qui recusandae tempore. Dolor, et soluta. Adipisci atque cum distinctio eius harum hic in itaque labore saepe velit! Ad doloremque excepturi facilis fugit ipsa magnam neque nobis nulla numquam quibusdam repellat reprehenderit sit, totam vel voluptatum. Aliquam architecto asperiores aspernatur atque beatae debitis, deleniti dolores ea enim eos facilis fugiat harum id illum inventore ipsa itaque iure laborum magnam nostrum obcaecati odit pariatur praesentium quaerat quo quos repellat sunt tempora voluptatem voluptatibus. Ad dolor ea eum sit ullam. Accusamus amet asperiores aut corporis dolorum ducimus enim, facere itaque laudantium modi mollitia nesciunt nulla odio provident quia quisquam ratione sit temporibus. Ab ad alias, aliquam aspernatur beatae consequatur corporis cupiditate dolorem doloremque earum, enim eos error harum illo illum in incidunt inventore ipsam magnam maiores neque perferendis possimus quae repellat reprehenderit saepe sapiente sit tempora voluptas voluptate? Alias amet animi consequatur debitis deserunt incidunt magnam maiores molestiae molestias numquam officia officiis perspiciatis placeat possimus, provident quibusdam suscipit unde veritatis voluptatem voluptatum! Exercitationem facere ipsa iste maxime nihil odit porro soluta ullam! Asperiores dolorem itaque maxime minus officiis perferendis repellat. Ab accusantium error eveniet fugit odit quaerat qui quis sequi sunt, voluptatibus? Amet, aspernatur consequatur ipsum iusto mollitia nihil nisi perspiciatis praesentium, rerum tempora vel voluptates voluptatibus?',
      img: 'https://fotorelax.ru/wp-content/uploads/2017/02/Top-10-most-beautiful-waterfalls-in-the-world-00.jpg',
      price: '1234',
    },
    {
      id: 2,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos, facilis magni non nulla quaerat vel.',
      img: 'https://fotovideoforum.ru/gallery/image.php?album_id=333&image_id=5500',
      price: '1234',
    },
    {
      id: 3,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores eligendi eos eveniet fugiat labore minima pariatur perferendis perspiciatis reprehenderit vitae. Accusamus aperiam cum cupiditate, deserunt dolorem dolores ducimus eaque eius eligendi error esse excepturi facere id impedit in, incidunt, iure laborum modi molestias nesciunt optio perferendis possimus quae qui quo quod quos recusandae saepe sapiente sit soluta sunt temporibus vel veritatis vitae voluptas voluptate. Aliquam aperiam at culpa, deserunt eaque et iure libero magni modi nihil nulla odio perspiciatis, provident quas recusandae reprehenderit sed ullam voluptatibus! Asperiores debitis inventore ipsam molestias qui? Ducimus laboriosam quam qui recusandae tempore. Dolor, et soluta. Adipisci atque cum distinctio eius harum hic in itaque labore saepe velit! Ad doloremque excepturi facilis fugit ipsa magnam neque nobis nulla numquam quibusdam repellat reprehenderit sit, totam vel voluptatum. Aliquam architecto asperiores aspernatur atque beatae debitis, deleniti dolores ea enim eos facilis fugiat harum id illum inventore ipsa itaque iure laborum magnam nostrum obcaecati odit pariatur praesentium quaerat quo quos repellat sunt tempora voluptatem voluptatibus. Ad dolor ea eum sit ullam. Accusamus amet asperiores aut corporis dolorum ducimus enim, facere itaque laudantium modi mollitia nesciunt nulla odio provident quia quisquam ratione sit temporibus. Ab ad alias, aliquam aspernatur beatae consequatur corporis cupiditate dolorem doloremque earum, enim eos error harum illo illum in incidunt inventore ipsam magnam maiores neque perferendis possimus quae repellat reprehenderit saepe sapiente sit tempora voluptas voluptate? Alias amet animi consequatur debitis deserunt incidunt magnam maiores molestiae molestias numquam officia officiis perspiciatis placeat possimus, provident quibusdam suscipit unde veritatis voluptatem voluptatum! Exercitationem facere ipsa iste maxime nihil odit porro soluta ullam! Asperiores dolorem itaque maxime minus officiis perferendis repellat. Ab accusantium error eveniet fugit odit quaerat qui quis sequi sunt, voluptatibus? Amet, aspernatur consequatur ipsum iusto mollitia nihil nisi perspiciatis praesentium, rerum tempora vel voluptates voluptatibus?',
      img: 'https://vsegda-pomnim.com/uploads/posts/2022-05/1651451574_5-vsegda-pomnim-com-p-krasivie-vodopadi-rossii-foto-5.jpg',
      price: '1234',
    },
    {
      id: 4,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores eligendi eos eveniet fugiat labore minima pariatur perferendis perspiciatis reprehenderit vitae. Accusamus aperiam cum cupiditate, deserunt dolorem dolores ducimus eaque eius eligendi error esse excepturi facere id impedit in, incidunt, iure laborum modi molestias nesciunt optio perferendis possimus quae qui quo quod quos recusandae saepe sapiente sit soluta sunt temporibus vel veritatis vitae voluptas voluptate. Aliquam aperiam at culpa, deserunt eaque et iure libero magni modi nihil nulla odio perspiciatis, provident quas recusandae reprehenderit sed ullam voluptatibus! Asperiores debitis inventore ipsam molestias qui? Ducimus laboriosam quam qui recusandae tempore. Dolor, et soluta. Adipisci atque cum distinctio eius harum hic in itaque labore saepe velit! Ad doloremque excepturi facilis fugit ipsa magnam neque nobis nulla numquam quibusdam repellat reprehenderit sit, totam vel voluptatum. Aliquam architecto asperiores aspernatur atque beatae debitis, deleniti dolores ea enim eos facilis fugiat harum id illum inventore ipsa itaque iure laborum magnam nostrum obcaecati odit pariatur praesentium quaerat quo quos repellat sunt tempora voluptatem voluptatibus. Ad dolor ea eum sit ullam. Accusamus amet asperiores aut corporis dolorum ducimus enim, facere itaque laudantium modi mollitia nesciunt nulla odio provident quia quisquam ratione sit temporibus. Ab ad alias, aliquam aspernatur beatae consequatur corporis cupiditate dolorem doloremque earum, enim eos error harum illo illum in incidunt inventore ipsam magnam maiores neque perferendis possimus quae repellat reprehenderit saepe sapiente sit tempora voluptas voluptate? Alias amet animi consequatur debitis deserunt incidunt magnam maiores molestiae molestias numquam officia officiis perspiciatis placeat possimus, provident quibusdam suscipit unde veritatis voluptatem voluptatum! Exercitationem facere ipsa iste maxime nihil odit porro soluta ullam! Asperiores dolorem itaque maxime minus officiis perferendis repellat. Ab accusantium error eveniet fugit odit quaerat qui quis sequi sunt, voluptatibus? Amet, aspernatur consequatur ipsum iusto mollitia nihil nisi perspiciatis praesentium, rerum tempora vel voluptates voluptatibus?',
      img: 'https://waterfal.ru/wp-content/uploads/2020/04/32-многошаговый-водопад-scaled-e1586176716467-2048x1341.jpg',
      price: '1234',
    },
    {
      id: 5,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores eligendi eos eveniet fugiat labore minima pariatur perferendis perspiciatis reprehenderit vitae. Accusamus aperiam cum cupiditate, deserunt dolorem dolores ducimus eaque eius eligendi error esse excepturi facere id impedit in, incidunt, iure laborum modi molestias nesciunt optio perferendis possimus quae qui quo quod quos recusandae saepe sapiente sit soluta sunt temporibus vel veritatis vitae voluptas voluptate. Aliquam aperiam at culpa, deserunt eaque et iure libero magni modi nihil nulla odio perspiciatis, provident quas recusandae reprehenderit sed ullam voluptatibus! Asperiores debitis inventore ipsam molestias qui? Ducimus laboriosam quam qui recusandae tempore. Dolor, et soluta. Adipisci atque cum distinctio eius harum hic in itaque labore saepe velit! Ad doloremque excepturi facilis fugit ipsa magnam neque nobis nulla numquam quibusdam repellat reprehenderit sit, totam vel voluptatum. Aliquam architecto asperiores aspernatur atque beatae debitis, deleniti dolores ea enim eos facilis fugiat harum id illum inventore ipsa itaque iure laborum magnam nostrum obcaecati odit pariatur praesentium quaerat quo quos repellat sunt tempora voluptatem voluptatibus. Ad dolor ea eum sit ullam. Accusamus amet asperiores aut corporis dolorum ducimus enim, facere itaque laudantium modi mollitia nesciunt nulla odio provident quia quisquam ratione sit temporibus. Ab ad alias, aliquam aspernatur beatae consequatur corporis cupiditate dolorem doloremque earum, enim eos error harum illo illum in incidunt inventore ipsam magnam maiores neque perferendis possimus quae repellat reprehenderit saepe sapiente sit tempora voluptas voluptate? Alias amet animi consequatur debitis deserunt incidunt magnam maiores molestiae molestias numquam officia officiis perspiciatis placeat possimus, provident quibusdam suscipit unde veritatis voluptatem voluptatum! Exercitationem facere ipsa iste maxime nihil odit porro soluta ullam! Asperiores dolorem itaque maxime minus officiis perferendis repellat. Ab accusantium error eveniet fugit odit quaerat qui quis sequi sunt, voluptatibus? Amet, aspernatur consequatur ipsum iusto mollitia nihil nisi perspiciatis praesentium, rerum tempora vel voluptates voluptatibus?',
      img: 'https://druzhniy-center.ru/wp-content/uploads/6/9/1/691917f95bc24361da891a0cac100b79.jpeg',
      price: '1234',
    },
    {
      id: 6,
      title: 'Lorem ipsum',
      description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores eligendi eos eveniet fugiat labore minima pariatur perferendis perspiciatis reprehenderit vitae. Accusamus aperiam cum cupiditate, deserunt dolorem dolores ducimus eaque eius eligendi error esse excepturi facere id impedit in, incidunt, iure laborum modi molestias nesciunt optio perferendis possimus quae qui quo quod quos recusandae saepe sapiente sit soluta sunt temporibus vel veritatis vitae voluptas voluptate. Aliquam aperiam at culpa, deserunt eaque et iure libero magni modi nihil nulla odio perspiciatis, provident quas recusandae reprehenderit sed ullam voluptatibus! Asperiores debitis inventore ipsam molestias qui? Ducimus laboriosam quam qui recusandae tempore. Dolor, et soluta. Adipisci atque cum distinctio eius harum hic in itaque labore saepe velit! Ad doloremque excepturi facilis fugit ipsa magnam neque nobis nulla numquam quibusdam repellat reprehenderit sit, totam vel voluptatum. Aliquam architecto asperiores aspernatur atque beatae debitis, deleniti dolores ea enim eos facilis fugiat harum id illum inventore ipsa itaque iure laborum magnam nostrum obcaecati odit pariatur praesentium quaerat quo quos repellat sunt tempora voluptatem voluptatibus. Ad dolor ea eum sit ullam. Accusamus amet asperiores aut corporis dolorum ducimus enim, facere itaque laudantium modi mollitia nesciunt nulla odio provident quia quisquam ratione sit temporibus. Ab ad alias, aliquam aspernatur beatae consequatur corporis cupiditate dolorem doloremque earum, enim eos error harum illo illum in incidunt inventore ipsam magnam maiores neque perferendis possimus quae repellat reprehenderit saepe sapiente sit tempora voluptas voluptate? Alias amet animi consequatur debitis deserunt incidunt magnam maiores molestiae molestias numquam officia officiis perspiciatis placeat possimus, provident quibusdam suscipit unde veritatis voluptatem voluptatum! Exercitationem facere ipsa iste maxime nihil odit porro soluta ullam! Asperiores dolorem itaque maxime minus officiis perferendis repellat. Ab accusantium error eveniet fugit odit quaerat qui quis sequi sunt, voluptatibus? Amet, aspernatur consequatur ipsum iusto mollitia nihil nisi perspiciatis praesentium, rerum tempora vel voluptates voluptatibus?',
      img: 'https://w-dog.ru/wallpapers/10/19/554853989098672/kirkjufoss-grundarfjordur-islandiya-gryundarfrdyur-vodopad-gory.jpg',
      price: '1234',
    },
  ]
})

export const getters = {
  getLastID(state) {
    let temp = [];
    Object.assign(temp, state.items);
    return temp.reverse()[0].id;
  }
}

export const mutations = {
  addProduct(state, product) {
    state.items.push(product);
  },
  removeProduct(state, id) {
    state.items = state.items.filter(el => el.id !== id);
  }
}
